language: python

python:
  - 3.8

before_install:
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install --editable ".[all]"
  - pip install pytest pytest-cov coverage pathlib

script:
  - pytest

notifications:
  email:
    recipients:
      - juan@prowellplan.com
    on_success: change
    on_failure: change